import "../styles/globals.css"
import Head from "next/head";
import Link from "next/link"

const MyApp = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Commerce app</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <nav className="nav">
      <Link href="/">Home</Link>
    </nav>

    <Component {...pageProps} />
  </>
)

export default MyApp
